languageCode = "en-us"
title = "Dark Simplicity"
baseurl = "https://sangpotado.github.io/"
theme = "darksimplicity"
min_version = "0.57.0"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
canonifyurls = true

[params]
description = "A Dark Minimalist Theme for Hugo"
copyright = "&copy Copyright 2017-2019. Matt Rhone and Dark Simplicity."
mainSections = ["post"]
#google_analytics_id=""
#disqus_shortname=""

[taxonomies]
tag = "tags"

[menu]
  [[menu.top]]
  name = "Facebook"
  pre = ""
  weight = -100
  url = "http://www.facebook.com/pepeandlife"
  [[menu.top]]
  name = "RSS"
  pre = ""
  weight = -90
  url = "index.xml"
